### ISSUE TITLE
go-tcp-transport and go-peerstream is incompatible for go-libp2p-transport version

### ISSUE THREAD

**Issue by LeonLi000** [libp2p/go-peerstream#10]
go-peerstream depend on  go-libp2p-transport  @ version 2.2.8
go-tcp-transport depend on  go-libp2p-transport  @ version 3.0.0
but go-libp2p-transport  @ version 3.0.0 and go-libp2p-transport  @ version 2.2.8 is incompatible

**Comment by Stebalien** [comment]
Unfortunately, we're in the process of pulling through some changes to how transports work. Currently, I recommend you use:

1. The hotfix/1.2.3 branch of go-tcp-transport (version 1.2.3).
2. Version 2.2.8 of go-libp2p-transport.

If you use `gx` to manage deps, this should "just work".

**Comment by LeonLi000** [comment]
Thanks, It`s working now.
